[package]
name = "surreal_test"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
surrealdb = "1.5.5"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
